config/routes.rb
Rails.application.routes.draw do

	get 'index' => 'dashboard#index', :as => 'index'
	get 'theme' => 'dashboard#theme', :as => 'theme'
	get 'login' => 'dashboard#login', :as => 'login'
	get 'register' => 'dashboard#register', :as => 'register'

	root :to => 'dashboard#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
		$nav = %w(cached code build class face home info work email data_usage pie_chart cloud computer)
  end

  def theme
  end

  def login
  end

  def register
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/layout_helper.rb
module LayoutHelper

  def title(page_title, show_topbar = true, show_sidebar = true)
    content_for(:title) { page_title.to_s }
		@show_sidebar = show_sidebar
		@show_topbar = show_topbar
  end

	def show_sidebar?
	  @show_sidebar
	end

	def show_topbar?
	  @show_topbar
	end

end

app/views/dashboard/index.html.erb
<% title "Index", true, true  %>

<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

app/views/dashboard/login.html.erb
<% title "Index", false, false  %>

<section class="auth-box">

	<div class="auth-bg" style="background-image:url(<%= image_path('old-typewriter.jpg') %>)"></div>
	<div class="login-card card">
		<div class="card-header">
			<span class="banner">
				<b>admin</b>istrate
			</span>
		</div>
		<div class="card-body">
			<form class="form-material" data-mudhead-form="true">
				<p class="auth-msg">Sign in to start your session</p>

				<div class="md-wrapper fw">
					<input type="text" class="md-input" />
					<label class="md-label" >Username</label>
					<div class="md-ripple"></div>
				</div>

				<div class="md-wrapper fw">
					<input type="password" class="md-input" />
					<label class="md-label" >Password</label>
					<div class="md-ripple"></div>
				</div>

				<div class="md-wrapper">
					<input type="submit" role="button" class="md-btn md-raised" />
				</div>
				<div>
					<div class="col-xs-12">
						<small>Don't have an account?</small>
						<b><a href="#" class="text-primary">Register</a></b>
					</div>
				</div>
			</form>
		</div>
	</div>
</section>

app/views/dashboard/register.html.erb
<% title "Register", true, true  %>

<h1>Dashboard#register</h1>
<p>Find me in app/views/dashboard/register.html.erb</p>

app/views/dashboard/theme.html.erb
<% title "Theme", true, true  %>

<h1>Dashboard#theme</h1>
<p>Find me in app/views/dashboard/theme.html.erb</p>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en" class="rykn0wxx no-js">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="author" content="rykn0wxx" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui" />
		<title>
			<%= content_for?(:title) ? yield(:title) + " | rykn0wxx" : "rykn0wxx" %>
		</title>
		<link rel="icon" type="image/x-icon" href="favicon.ico" />
		<script type="text/javascript">
			document.documentElement.className = "rykn0wxx js";
		</script>

		<%= tag :meta, name: 'turbolinks-root', content: '/' %>
		<%= tag :meta, name: 'turbolinks-cache-control', content: 'no-preview' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

		<%= render "shared/styles_css" %>

		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="show-sidebar <%= controller.action_name %>">

		<div class="md-content wrapper"> <!-- wrapper -->

			<div class="layout-row">

				<%= render "shared/sidebar" if show_sidebar? %>

				<div class="layout-column flex content-wrapper">

					<%= render "shared/topbar" if show_topbar? %>

					<main class="main-content">
						<%= yield %>
					</main>
				</div>

			</div>

		</div>  <!-- wrapper -->

		<%= render "shared/scripts_js" %>
  </body>
</html>

app/views/shared/_scripts_js.html.erb
<% content_for(:javascript) do %>
	<%= javascript_include_tag 'app', 'data-turbolinks-suppress-warning':'true' %>
<% end %>

<%= yield :javascript %>

app/views/shared/_sidebar.html.erb
<aside class="main-sidebar md-whiteframe-z2">
	<header class="sidebar-heading">
		<%= link_to root_path, :class => "logo" do %>
		  <span class="logo-mini">
		  	<b>a</b>dm
		  </span>
			<span class="logo-lg">
				<b>admin</b>istrate
			</span>
		<% end %>
	</header>
	<div class="sidebar-content md-content flex" data-plugin="ps">
		<nav class="side-nav">
			<ul class="sidebar-menu tree nav nav-stacked" data-plugin="metis">
				<li class="tree-item nav-item">
					<%= link_to root_path, :class => "tree-link nav-link" do %>
						<span class="nav-icon"><i class="material-icons">build</i></span>
						<span class="nav-title">Index</span>
					<% end %>
				</li>
				<li class="tree-item nav-item">
					<%= link_to theme_path, :class => "tree-link nav-link" do %>
						<span class="nav-icon"><i class="material-icons">class</i></span>
						<span class="nav-title">Theme</span>
					<% end %>
				</li>
				<li class="tree-item nav-item">
					<%= link_to login_path, :class => "tree-link nav-link" do %>
						<span class="nav-icon"><i class="material-icons">work</i></span>
						<span class="nav-title">Login</span>
					<% end %>
				</li>
				<li class="tree-item nav-item">
					<%= link_to register_path, :class => "tree-link nav-link" do %>
						<span class="nav-icon"><i class="material-icons">data_usage</i></span>
						<span class="nav-title">Register</span>
					<% end %>
				</li>
			</ul>
		</nav>
	</div>
</aside>

app/views/shared/_styles_css.html.erb
<% content_for(:css_styles) do %>
	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<% end %>

<%= yield :css_styles %>

app/views/shared/_topbar.html.erb
<header class="main-header md-whiteframe-glow-z1 md-toolbar _md-toolbar-transitions">

	<div class="md-toolbar-tools">

		<button class="md-icon-btn md-btn" data-toggle="push-menu">
			<div class="md-icon">
				<%= mi.menu %>
			</div>
		</button>

	</div>

</header>